backend:
  name: git-gateway
  branch: main

media_folder: "src/img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
